-- Catalogo inicial de ejercicios comunes. Punto de partida editable.
insert into public.exercises (name, muscle_group) values
  ('Press de banca con barra', 'pecho'),
  ('Press inclinado con mancuernas', 'pecho'),
  ('Aperturas con mancuernas', 'pecho'),
  ('Fondos en paralelas', 'pecho'),
  ('Cruce de poleas', 'pecho'),
  ('Dominadas', 'espalda'),
  ('Remo con barra', 'espalda'),
  ('Remo con mancuerna', 'espalda'),
  ('Jalon al pecho', 'espalda'),
  ('Remo en polea baja', 'espalda'),
  ('Peso muerto', 'espalda'),
  ('Sentadilla con barra', 'piernas'),
  ('Prensa de piernas', 'piernas'),
  ('Extension de cuadriceps', 'piernas'),
  ('Curl femoral', 'piernas'),
  ('Peso muerto rumano', 'piernas'),
  ('Zancadas', 'piernas'),
  ('Elevacion de gemelos', 'piernas'),
  ('Hip thrust', 'gluteos'),
  ('Press militar con barra', 'hombros'),
  ('Press de hombros con mancuernas', 'hombros'),
  ('Elevaciones laterales', 'hombros'),
  ('Elevaciones frontales', 'hombros'),
  ('Pajaros (deltoide posterior)', 'hombros'),
  ('Curl de biceps con barra', 'biceps'),
  ('Curl de biceps con mancuernas', 'biceps'),
  ('Curl martillo', 'biceps'),
  ('Curl en banco scott', 'biceps'),
  ('Extension de triceps en polea', 'triceps'),
  ('Press frances', 'triceps'),
  ('Fondos en banco', 'triceps'),
  ('Patada de triceps', 'triceps'),
  ('Plancha abdominal', 'core'),
  ('Crunch abdominal', 'core'),
  ('Elevacion de piernas colgado', 'core'),
  ('Rueda abdominal', 'core'),
  ('Russian twist', 'core')
on conflict do nothing;;
