-- Catalogo curado a partir de hasaneyldrm/exercises-dataset (datos MIT).
-- Seleccion manual de 198 ejercicios de gimnasio comunes, con el nombre
-- traducido al espanol y el original conservado en name_en para poder buscarlos
-- con cualquiera de los dos.

-- El unico ejercicio que habia era de prueba y ya no lo referencia nadie: la
-- reestructuracion a rutinas y dias borro las tablas que lo usaban.
delete from public.exercises;

insert into public.exercises (slug, name, name_en, source_id, equipment) values
  ('press-de-banca-con-barra', 'Press de banca con barra', 'barbell bench press', '0025', 'barra'),
  ('press-inclinado-con-barra', 'Press inclinado con barra', 'barbell incline bench press', '0047', 'barra'),
  ('press-declinado-con-barra', 'Press declinado con barra', 'barbell decline bench press', '0033', 'barra'),
  ('press-de-banca-agarre-ancho-con-barra', 'Press de banca agarre ancho con barra', 'barbell wide bench press', '0122', 'barra'),
  ('press-de-banca-con-mancuernas', 'Press de banca con mancuernas', 'dumbbell bench press', '0289', 'mancuernas'),
  ('press-inclinado-con-mancuernas', 'Press inclinado con mancuernas', 'dumbbell incline bench press', '0314', 'mancuernas'),
  ('press-declinado-con-mancuernas', 'Press declinado con mancuernas', 'dumbbell decline bench press', '0301', 'mancuernas'),
  ('aperturas-con-mancuernas', 'Aperturas con mancuernas', 'dumbbell fly', '0308', 'mancuernas'),
  ('aperturas-inclinadas-con-mancuernas', 'Aperturas inclinadas con mancuernas', 'dumbbell incline fly', '0319', 'mancuernas'),
  ('aperturas-declinadas-con-mancuernas', 'Aperturas declinadas con mancuernas', 'dumbbell decline fly', '0302', 'mancuernas'),
  ('pullover-con-mancuerna', 'Pullover con mancuerna', 'dumbbell pullover', '0375', 'mancuernas'),
  ('press-inclinado-agarre-neutro-con-mancuernas', 'Press inclinado agarre neutro con mancuernas', 'dumbbell incline hammer press', '0321', 'mancuernas'),
  ('press-agarre-neutro-con-mancuernas', 'Press agarre neutro con mancuernas', 'dumbbell lying hammer press', '0340', 'mancuernas'),
  ('cruce-de-poleas', 'Cruce de poleas', 'cable cross-over variation', '0155', 'polea'),
  ('aperturas-en-polea-de-pie', 'Aperturas en polea de pie', 'cable standing fly', '0227', 'polea'),
  ('aperturas-en-polea-a-media-altura', 'Aperturas en polea a media altura', 'cable middle fly', '0188', 'polea'),
  ('aperturas-en-polea-baja', 'Aperturas en polea baja', 'cable low fly', '0179', 'polea'),
  ('aperturas-en-polea-inclinado', 'Aperturas en polea inclinado', 'cable incline fly', '0171', 'polea'),
  ('press-de-pecho-en-maquina', 'Press de pecho en maquina', 'lever chest press', '0577', 'maquina'),
  ('press-inclinado-en-maquina', 'Press inclinado en maquina', 'lever incline chest press', '1299', 'maquina'),
  ('aperturas-en-maquina', 'Aperturas en maquina', 'lever seated fly', '0596', 'maquina'),
  ('fondos-en-paralelas', 'Fondos en paralelas', 'chest dip', '0251', 'peso corporal'),
  ('flexiones-de-brazos', 'Flexiones de brazos', 'push-up', '0662', 'peso corporal'),
  ('flexiones-inclinadas', 'Flexiones inclinadas', 'incline push-up', '0493', 'peso corporal'),
  ('flexiones-declinadas', 'Flexiones declinadas', 'decline push-up', '0279', 'peso corporal'),
  ('press-de-banca-en-multipower', 'Press de banca en multipower', 'smith bench press', '0748', 'multipower'),
  ('press-inclinado-en-multipower', 'Press inclinado en multipower', 'smith incline bench press', '0757', 'multipower'),
  ('dominadas', 'Dominadas', 'pull-up', '0652', 'peso corporal'),
  ('dominadas-supinas', 'Dominadas supinas', 'chin-up', '1326', 'peso corporal'),
  ('dominadas-agarre-ancho', 'Dominadas agarre ancho', 'wide grip pull-up', '1429', 'peso corporal'),
  ('jalon-al-pecho', 'Jalon al pecho', 'cable pulldown', '0198', 'polea'),
  ('jalon-al-pecho-con-triangulo', 'Jalon al pecho con triangulo', 'cable lateral pulldown with v-bar', '2616', 'polea'),
  ('jalon-al-pecho-con-barra', 'Jalon al pecho con barra', 'cable bar lateral pulldown', '0150', 'polea'),
  ('jalon-con-brazos-extendidos', 'Jalon con brazos extendidos', 'cable straight arm pulldown', '0238', 'polea'),
  ('remo-sentado-en-polea', 'Remo sentado en polea', 'cable seated row', '0861', 'polea'),
  ('remo-sentado-en-polea-con-cuerda', 'Remo sentado en polea con cuerda', 'cable rope seated row', '1323', 'polea'),
  ('jalon-a-una-mano', 'Jalon a una mano', 'cable one arm pulldown', '3563', 'polea'),
  ('remo-con-barra', 'Remo con barra', 'barbell bent over row', '0027', 'barra'),
  ('remo-con-barra-agarre-supino', 'Remo con barra agarre supino', 'barbell reverse grip bent over row', '0118', 'barra'),
  ('remo-pendlay', 'Remo Pendlay', 'barbell pendlay row', '3017', 'barra'),
  ('remo-con-barra-a-una-mano', 'Remo con barra a una mano', 'barbell one arm bent over row', '0064', 'barra'),
  ('encogimientos-con-barra', 'Encogimientos con barra', 'barbell shrug', '0095', 'barra'),
  ('pullover-con-barra', 'Pullover con barra', 'barbell pullover', '0073', 'barra'),
  ('remo-con-mancuernas', 'Remo con mancuernas', 'dumbbell bent over row', '0293', 'mancuernas'),
  ('remo-a-una-mano-con-mancuerna', 'Remo a una mano con mancuerna', 'dumbbell one arm bent-over row', '0292', 'mancuernas'),
  ('remo-inclinado-con-mancuernas', 'Remo inclinado con mancuernas', 'dumbbell incline row', '0327', 'mancuernas'),
  ('encogimientos-con-mancuernas', 'Encogimientos con mancuernas', 'dumbbell shrug', '0406', 'mancuernas'),
  ('remo-en-maquina', 'Remo en maquina', 'lever bent over row', '0574', 'barra'),
  ('remo-en-maquina-a-una-mano', 'Remo en maquina a una mano', 'lever one arm bent over row', '0589', 'barra'),
  ('remo-sentado-en-maquina', 'Remo sentado en maquina', 'lever seated row', '1350', 'maquina'),
  ('jalon-frontal-en-maquina', 'Jalon frontal en maquina', 'lever front pulldown', '0579', 'maquina'),
  ('remo-invertido', 'Remo invertido', 'inverted row', '0499', 'peso corporal'),
  ('remo-en-multipower', 'Remo en multipower', 'smith bent over row', '1359', 'multipower'),
  ('encogimientos-en-multipower', 'Encogimientos en multipower', 'smith shrug', '0767', 'multipower'),
  ('press-militar-de-pie', 'Press militar de pie', 'barbell standing wide military press', '1457', 'barra'),
  ('press-militar-sentado', 'Press militar sentado', 'barbell seated overhead press', '0091', 'barra'),
  ('elevaciones-frontales-con-barra', 'Elevaciones frontales con barra', 'barbell front raise', '0041', 'barra'),
  ('remo-al-menton-con-barra', 'Remo al menton con barra', 'barbell upright row', '0120', 'barra'),
  ('elevaciones-posteriores-con-barra', 'Elevaciones posteriores con barra', 'barbell rear delt raise', '0075', 'barra'),
  ('press-de-hombros-sentado', 'Press de hombros sentado', 'dumbbell seated shoulder press', '0405', 'mancuernas'),
  ('press-arnold', 'Press Arnold', 'dumbbell arnold press', '2137', 'mancuernas'),
  ('elevaciones-laterales', 'Elevaciones laterales', 'dumbbell lateral raise', '0334', 'mancuernas'),
  ('elevaciones-frontales-con-mancuernas', 'Elevaciones frontales con mancuernas', 'dumbbell front raise', '0310', 'mancuernas'),
  ('pajaros-con-mancuernas', 'Pajaros con mancuernas', 'dumbbell rear fly', '0378', 'mancuernas'),
  ('aperturas-invertidas-con-mancuernas', 'Aperturas invertidas con mancuernas', 'dumbbell reverse fly', '0383', 'mancuernas'),
  ('remo-al-menton-con-mancuernas', 'Remo al menton con mancuernas', 'dumbbell upright row', '0437', 'mancuernas'),
  ('push-press-con-mancuernas', 'Push press con mancuernas', 'dumbbell push press', '1700', 'mancuernas'),
  ('elevaciones-laterales-en-polea', 'Elevaciones laterales en polea', 'cable lateral raise', '0178', 'polea'),
  ('elevacion-lateral-en-polea-a-una-mano', 'Elevacion lateral en polea a una mano', 'cable one arm lateral raise', '0192', 'polea'),
  ('elevaciones-frontales-en-polea', 'Elevaciones frontales en polea', 'cable front raise', '0162', 'polea'),
  ('pajaros-en-polea-sentado', 'Pajaros en polea sentado', 'cable seated rear lateral raise', '0215', 'polea'),
  ('remo-al-menton-en-polea', 'Remo al menton en polea', 'cable upright row', '0246', 'polea'),
  ('press-de-hombros-en-maquina', 'Press de hombros en maquina', 'lever shoulder press', '0603', 'maquina'),
  ('pajaros-en-maquina', 'Pajaros en maquina', 'lever seated reverse fly', '0602', 'maquina'),
  ('press-de-hombros-en-multipower', 'Press de hombros en multipower', 'smith shoulder press', '0766', 'multipower'),
  ('remo-al-menton-en-multipower', 'Remo al menton en multipower', 'smith upright row', '0775', 'multipower'),
  ('curl-con-barra', 'Curl con barra', 'barbell curl', '0031', 'barra'),
  ('curl-predicador-con-barra', 'Curl predicador con barra', 'barbell preacher curl', '0070', 'barra'),
  ('curl-invertido-con-barra', 'Curl invertido con barra', 'barbell reverse curl', '0080', 'barra'),
  ('curl-de-arrastre', 'Curl de arrastre', 'barbell drag curl', '0038', 'barra'),
  ('curl-con-barra-agarre-ancho', 'Curl con barra agarre ancho', 'barbell standing wide-grip curl', '0113', 'barra'),
  ('curl-con-barra-agarre-cerrado', 'Curl con barra agarre cerrado', 'barbell standing close grip curl', '0106', 'barra'),
  ('curl-con-mancuernas', 'Curl con mancuernas', 'dumbbell biceps curl', '0294', 'mancuernas'),
  ('curl-alterno-con-mancuernas', 'Curl alterno con mancuernas', 'dumbbell alternate biceps curl', '0285', 'mancuernas'),
  ('curl-martillo', 'Curl martillo', 'dumbbell hammer curl', '0313', 'mancuernas'),
  ('curl-inclinado-con-mancuernas', 'Curl inclinado con mancuernas', 'dumbbell incline curl', '0318', 'mancuernas'),
  ('curl-predicador-con-mancuerna', 'Curl predicador con mancuerna', 'dumbbell preacher curl', '0372', 'mancuernas'),
  ('curl-sentado-con-mancuernas', 'Curl sentado con mancuernas', 'dumbbell seated curl', '0391', 'mancuernas'),
  ('curl-concentrado-en-polea', 'Curl concentrado en polea', 'cable concentration curl', '1631', 'polea'),
  ('curl-zottman', 'Curl Zottman', 'dumbbell zottman curl', '0439', 'mancuernas'),
  ('curl-en-polea', 'Curl en polea', 'cable curl', '0868', 'polea'),
  ('curl-en-polea-a-una-mano', 'Curl en polea a una mano', 'cable one arm curl', '0190', 'polea'),
  ('curl-martillo-en-polea-con-cuerda', 'Curl martillo en polea con cuerda', 'cable hammer curl (with rope)', '0165', 'polea'),
  ('curl-predicador-en-polea', 'Curl predicador en polea', 'cable preacher curl', '0195', 'polea'),
  ('curl-con-barra-z', 'Curl con barra Z', 'ez barbell curl', '0447', 'barra Z'),
  ('curl-con-barra-z-y-arm-blaster', 'Curl con barra Z y arm blaster', 'ez-bar biceps curl (with arm blaster)', '2404', 'barra Z'),
  ('extension-de-triceps-en-polea', 'Extension de triceps en polea', 'cable pushdown', '0201', 'polea'),
  ('extension-de-triceps-con-cuerda', 'Extension de triceps con cuerda', 'cable pushdown (with rope attachment)', '0200', 'polea'),
  ('extension-de-triceps-agarre-supino', 'Extension de triceps agarre supino', 'cable reverse-grip pushdown', '0207', 'polea'),
  ('extension-de-triceps-sobre-la-cabeza-en-polea', 'Extension de triceps sobre la cabeza en polea', 'cable overhead triceps extension (rope attachment)', '0194', 'polea'),
  ('extension-de-triceps-en-polea-a-una-mano', 'Extension de triceps en polea a una mano', 'cable one arm tricep pushdown', '1723', 'polea'),
  ('press-cerrado-con-barra', 'Press cerrado con barra', 'barbell close-grip bench press', '0030', 'barra'),
  ('extension-de-triceps-tumbado-con-barra', 'Extension de triceps tumbado con barra', 'barbell lying triceps extension', '0061', 'barra'),
  ('press-frances', 'Press frances', 'barbell lying triceps extension skull crusher', '0060', 'barra'),
  ('extension-de-triceps-sentado-con-barra', 'Extension de triceps sentado con barra', 'barbell seated overhead triceps extension', '0092', 'barra'),
  ('extension-de-triceps-de-pie-con-barra', 'Extension de triceps de pie con barra', 'barbell standing overhead triceps extension', '0109', 'barra'),
  ('patada-de-triceps', 'Patada de triceps', 'dumbbell kickback', '0333', 'mancuernas'),
  ('patada-de-triceps-a-una-mano', 'Patada de triceps a una mano', 'dumbbell one arm kickback', '0354', 'mancuernas'),
  ('extension-de-triceps-sentado-con-mancuerna', 'Extension de triceps sentado con mancuerna', 'dumbbell seated triceps extension', '2188', 'mancuernas'),
  ('extension-de-triceps-de-pie-con-mancuerna', 'Extension de triceps de pie con mancuerna', 'dumbbell standing triceps extension', '0430', 'mancuernas'),
  ('extension-de-triceps-tumbado-con-mancuernas', 'Extension de triceps tumbado con mancuernas', 'dumbbell lying triceps extension', '0351', 'mancuernas'),
  ('press-cerrado-con-mancuernas', 'Press cerrado con mancuernas', 'dumbbell close grip press', '1731', 'mancuernas'),
  ('press-tate', 'Press Tate', 'dumbbell tate press', '0436', 'mancuernas'),
  ('fondos-de-triceps', 'Fondos de triceps', 'triceps dip', '0814', 'peso corporal'),
  ('fondos-en-banco', 'Fondos en banco', 'bench dip on floor', '1399', 'peso corporal'),
  ('flexiones-diamante', 'Flexiones diamante', 'diamond push-up', '0283', 'peso corporal'),
  ('flexiones-agarre-cerrado', 'Flexiones agarre cerrado', 'close-grip push-up', '0259', 'peso corporal'),
  ('press-frances-con-barra-z', 'Press frances con barra Z', 'ez bar standing french press', '1749', 'barra Z'),
  ('sentadilla-con-barra', 'Sentadilla con barra', 'barbell full squat', '0043', 'barra'),
  ('sentadilla-frontal', 'Sentadilla frontal', 'barbell front squat', '0042', 'barra'),
  ('sentadilla-barra-alta', 'Sentadilla barra alta', 'barbell high bar squat', '1436', 'barra'),
  ('sentadilla-barra-baja', 'Sentadilla barra baja', 'barbell low bar squat', '1435', 'barra'),
  ('sentadilla-stance-cerrado', 'Sentadilla stance cerrado', 'barbell narrow stance squat', '0063', 'barra'),
  ('sentadilla-stance-ancho', 'Sentadilla stance ancho', 'barbell wide squat', '0124', 'barra'),
  ('sentadilla-hack-con-barra', 'Sentadilla hack con barra', 'barbell hack squat', '0046', 'barra'),
  ('sentadilla-overhead', 'Sentadilla overhead', 'barbell overhead squat', '0069', 'barra'),
  ('sentadilla-bulgara-con-barra', 'Sentadilla bulgara con barra', 'barbell single leg split squat', '0099', 'barra'),
  ('sentadilla-goblet', 'Sentadilla goblet', 'dumbbell goblet squat', '1760', 'mancuernas'),
  ('sentadilla-bulgara-con-mancuernas', 'Sentadilla bulgara con mancuernas', 'dumbbell single leg split squat', '0410', 'mancuernas'),
  ('subida-al-cajon-con-mancuernas', 'Subida al cajon con mancuernas', 'dumbbell step-up lunge', '2796', 'mancuernas'),
  ('extension-de-cuadriceps-en-maquina', 'Extension de cuadriceps en maquina', 'lever leg extension', '0585', 'maquina'),
  ('prensa-a-una-pierna', 'Prensa a una pierna', 'sled 45 degrees one leg press', '1425', 'maquina'),
  ('prensa-en-multipower', 'Prensa en multipower', 'smith leg press', '0760', 'multipower'),
  ('sentadilla-en-multipower', 'Sentadilla en multipower', 'smith squat', '0770', 'multipower'),
  ('sentadilla-frontal-en-multipower', 'Sentadilla frontal en multipower', 'smith front squat (clean grip)', '1433', 'multipower'),
  ('sentadilla-sissy', 'Sentadilla sissy', 'sissy squat', '1489', 'peso corporal'),
  ('peso-muerto-con-barra', 'Peso muerto con barra', 'barbell deadlift', '0032', 'barra'),
  ('peso-muerto-sumo', 'Peso muerto sumo', 'barbell sumo deadlift', '0117', 'barra'),
  ('peso-muerto-rumano', 'Peso muerto rumano', 'barbell romanian deadlift', '0085', 'barra'),
  ('peso-muerto-a-una-pierna', 'Peso muerto a una pierna', 'barbell single leg deadlift', '1756', 'barra'),
  ('rack-pull', 'Rack pull', 'barbell rack pull', '0074', 'barra'),
  ('puente-de-gluteos-con-barra', 'Puente de gluteos con barra', 'barbell glute bridge', '1409', 'barra'),
  ('zancadas-con-barra', 'Zancadas con barra', 'barbell lunge', '0054', 'barra'),
  ('zancadas-hacia-atras-con-barra', 'Zancadas hacia atras con barra', 'barbell rear lunge', '0078', 'barra'),
  ('zancadas-laterales-con-barra', 'Zancadas laterales con barra', 'barbell lateral lunge', '1410', 'barra'),
  ('subida-al-cajon-con-barra', 'Subida al cajon con barra', 'barbell step-up', '0114', 'barra'),
  ('sentadilla-zercher', 'Sentadilla Zercher', 'barbell zercher squat', '0127', 'barra'),
  ('sentadilla-con-salto', 'Sentadilla con salto', 'barbell jump squat', '0053', 'barra'),
  ('peso-muerto-rumano-con-mancuernas', 'Peso muerto rumano con mancuernas', 'dumbbell romanian deadlift', '1459', 'mancuernas'),
  ('zancadas-con-mancuernas', 'Zancadas con mancuernas', 'dumbbell lunge', '0336', 'mancuernas'),
  ('zancadas-hacia-atras-con-mancuernas', 'Zancadas hacia atras con mancuernas', 'dumbbell rear lunge', '0381', 'mancuernas'),
  ('subida-al-cajon-con-mancuerna', 'Subida al cajon con mancuerna', 'dumbbell step-up', '0431', 'mancuernas'),
  ('peso-muerto-a-una-pierna-con-mancuerna', 'Peso muerto a una pierna con mancuerna', 'dumbbell single leg deadlift', '1757', 'mancuernas'),
  ('pull-through-en-polea', 'Pull through en polea', 'cable pull through (with rope)', '0196', 'polea'),
  ('extension-de-cadera-en-polea', 'Extension de cadera en polea', 'cable standing hip extension', '0228', 'polea'),
  ('abductores-en-maquina', 'Abductores en maquina', 'lever seated hip abduction', '0597', 'maquina'),
  ('puente-de-gluteos-en-el-suelo', 'Puente de gluteos en el suelo', 'low glute bridge on floor', '3013', 'peso corporal'),
  ('sentadilla-sumo-en-multipower', 'Sentadilla sumo en multipower', 'smith sumo squat', '3142', 'multipower'),
  ('curl-femoral-tumbado', 'Curl femoral tumbado', 'lever lying leg curl', '0586', 'maquina'),
  ('curl-femoral-sentado', 'Curl femoral sentado', 'lever seated leg curl', '0599', 'maquina'),
  ('curl-femoral-de-rodillas', 'Curl femoral de rodillas', 'lever kneeling leg curl', '0582', 'maquina'),
  ('peso-muerto-piernas-rigidas', 'Peso muerto piernas rigidas', 'barbell straight leg deadlift', '0116', 'barra'),
  ('buenos-dias-con-barra', 'Buenos dias con barra', 'barbell good morning', '0044', 'barra'),
  ('peso-muerto-piernas-rigidas-con-mancuernas', 'Peso muerto piernas rigidas con mancuernas', 'dumbbell straight leg deadlift', '0434', 'mancuernas'),
  ('elevacion-de-gluteo-e-isquios', 'Elevacion de gluteo e isquios', 'glute-ham raise', '3193', 'peso corporal'),
  ('elevacion-de-gemelos-de-pie-con-barra', 'Elevacion de gemelos de pie con barra', 'barbell standing calf raise', '1372', 'barra'),
  ('elevacion-de-gemelos-sentado-con-barra', 'Elevacion de gemelos sentado con barra', 'barbell seated calf raise', '0088', 'barra'),
  ('elevacion-de-gemelos-de-pie-con-mancuernas', 'Elevacion de gemelos de pie con mancuernas', 'dumbbell standing calf raise', '0417', 'mancuernas'),
  ('elevacion-de-gemelos-sentado-con-mancuernas', 'Elevacion de gemelos sentado con mancuernas', 'dumbbell seated calf raise', '1379', 'mancuernas'),
  ('elevacion-de-gemelos-a-una-pierna', 'Elevacion de gemelos a una pierna', 'dumbbell single leg calf raise', '0409', 'mancuernas'),
  ('elevacion-de-gemelos-en-maquina', 'Elevacion de gemelos en maquina', 'lever standing calf raise', '0605', 'maquina'),
  ('gemelos-sentado-en-maquina', 'Gemelos sentado en maquina', 'lever seated calf raise', '0594', 'maquina'),
  ('prensa-de-gemelos', 'Prensa de gemelos', 'lever calf press', '2289', 'maquina'),
  ('elevacion-de-gemelos-en-multipower', 'Elevacion de gemelos en multipower', 'smith standing leg calf raise', '0773', 'multipower'),
  ('elevacion-de-gemelos-en-polea', 'Elevacion de gemelos en polea', 'cable standing calf raise', '1375', 'polea'),
  ('curl-de-muneca-con-barra', 'Curl de muneca con barra', 'barbell wrist curl', '0126', 'barra'),
  ('curl-de-muneca-invertido-con-barra', 'Curl de muneca invertido con barra', 'barbell reverse wrist curl', '0082', 'barra'),
  ('curl-de-muneca-invertido-con-mancuernas', 'Curl de muneca invertido con mancuernas', 'dumbbell reverse wrist curl', '0385', 'mancuernas'),
  ('curl-de-muneca-a-una-mano', 'Curl de muneca a una mano', 'dumbbell one arm wrist curl', '0364', 'mancuernas'),
  ('curl-de-muneca-en-polea', 'Curl de muneca en polea', 'cable wrist curl', '0247', 'polea'),
  ('pronacion-con-mancuerna', 'Pronacion con mancuerna', 'dumbbell lying pronation', '0347', 'mancuernas'),
  ('supinacion-con-mancuerna', 'Supinacion con mancuerna', 'dumbbell lying supination', '0349', 'mancuernas'),
  ('crunch-en-polea-de-rodillas', 'Crunch en polea de rodillas', 'cable kneeling crunch', '0175', 'polea'),
  ('crunch-en-polea-sentado', 'Crunch en polea sentado', 'cable seated crunch', '0212', 'polea'),
  ('crunch-en-polea-de-pie', 'Crunch en polea de pie', 'cable standing crunch', '0226', 'polea'),
  ('crunch-invertido-en-polea', 'Crunch invertido en polea', 'cable reverse crunch', '0873', 'polea'),
  ('flexion-lateral-en-polea', 'Flexion lateral en polea', 'cable side bend', '0222', 'polea'),
  ('giro-en-polea', 'Giro en polea', 'cable twist', '0243', 'polea'),
  ('flexion-lateral-con-mancuerna', 'Flexion lateral con mancuerna', 'dumbbell side bend', '0407', 'mancuernas'),
  ('crunch-en-el-suelo', 'Crunch en el suelo', 'crunch floor', '0274', 'peso corporal'),
  ('abdominales-en-banco-declinado', 'Abdominales en banco declinado', 'decline sit-up', '0282', 'peso corporal'),
  ('elevacion-de-piernas-colgado', 'Elevacion de piernas colgado', 'hanging leg raise', '0472', 'peso corporal'),
  ('elevacion-de-piernas-rectas-colgado', 'Elevacion de piernas rectas colgado', 'hanging straight leg raise', '0475', 'peso corporal'),
  ('elevacion-de-piernas-en-silla-romana', 'Elevacion de piernas en silla romana', 'captains chair straight leg raise', '2963', 'peso corporal'),
  ('giro-ruso', 'Giro ruso', 'russian twist', '0687', 'peso corporal'),
  ('rueda-abdominal-con-barra', 'Rueda abdominal con barra', 'barbell rollerout', '0084', 'barra'),
  ('crunch-en-maquina', 'Crunch en maquina', 'lever seated crunch', '1452', 'maquina'),
  ('bicho-muerto', 'Bicho muerto', 'dead bug', '0276', 'peso corporal');

create unique index if not exists exercises_slug_key on public.exercises (slug);
alter table public.exercises alter column slug set not null;
